name: Issue moderator test

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  moderate:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Moderate the issue
        # uses: tachiyomiorg/issue-moderator-action@v2
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-label: duplicate
          duplicate-check-enabled: true
          duplicate-check-labels: |
            ["enhancement", "question"]
          existing-check-enabled: true
          existing-check-labels: |
            ["enhancement", "question"]
          auto-close-rules: |
            [
              {
                "type": "title",
                "regex": ".*Test title.*",
                "message": "The title was not updated."
              },
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed."
              },
              {
                "type": "body",
                "regex": ".*Test: \\?.*",
                "message": "The requested information was not filled out."
              },
              {
                "type": "both",
                "regex":".*(mangago|mangafox|hq\\s*dragon|manga\\s*host).*",
                "ignoreCase": true,
                "message": "{match} will not be added back as it is too difficult to maintain",
                "labels": ["wontfix", "invalid"]
              }
            ]
          auto-close-ignore-label: do-not-autoclose
          blurbs: |
            [
              {
                "keywords": ["cf", "cloudflare"],
                "message": "Refer to the **Solving Cloudflare issues** section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection."
              }
            ]
